require("aqothy.config.set")
require("aqothy.config.keymaps")
require("aqothy.config.lazy")
require("aqothy.config.autocmds")
require("aqothy.config.winbar")
require("aqothy.config.commands")
require("aqothy.config.statusline")
require("aqothy.config.colors")
