require("aqothy.config.options")
require("aqothy.config.keymaps")
require("aqothy.config.lazy")
require("aqothy.config.autocmds")
-- require("aqothy.config.winbar")
-- require("aqothy.config.term")
require("aqothy.config.commands")
require("aqothy.config.statusline")
require("aqothy.config.colors")
