return {
	-- "saghen/blink.cmp",
	-- version = "v0.*",
	-- event = "InsertEnter",
	-- dependencies = {
	-- 	"rafamadriz/friendly-snippets",
	-- 	{ "saghen/blink.compat", opts = { impersonate_nvim_cmp = true } },
	-- 	{ "saadparwaiz1/cmp_luasnip" },
	-- },
	-- opts_extend = {
	-- 	"sources.compat",
	-- 	"sources.default",
	-- },
	-- opts = {
	-- 	-- 'default' for mappings similar to built-in completion
	-- 	-- 'super-tab' for mappings similar to vscode (tab to accept, arrow keys to navigate)
	-- 	-- 'enter' for mappings similar to 'super-tab' but with 'enter' to accept
	-- 	-- see the "default configuration" section below for full documentation on how to define
	-- 	-- your own keymap.
	-- 	-- bruh the default keymap still overrides my other keymaps even though they're changed
	-- 	keymap = {
	-- 		["<C-enter>"] = { "select_and_accept", "fallback" },
	-- 		["<C-u>"] = { "scroll_documentation_up", "fallback" },
	-- 		["<C-d>"] = { "scroll_documentation_down", "fallback" },
	-- 		["<C-h>"] = { "hide", "fallback" },
	-- 		["<C-space>"] = { "show", "show_documentation", "hide_documentation" },
	-- 		["<C-p>"] = { "select_prev", "fallback" },
	-- 		["<C-n>"] = { "select_next", "fallback" },
	-- 	},
	--
	-- 	-- default list of enabled providers defined so that you can extend it
	-- 	-- elsewhere in your config, without redefining it, via `opts_extend`
	-- 	sources = {
	-- 		-- adding any nvim-cmp sources here will enable them
	-- 		-- with blink.compat
	-- 		compat = { "luasnip" },
	-- 		default = { "lsp", "path", "snippets", "buffer" },
	-- 		providers = {
	-- 			luasnip = {
	-- 				name = "luasnip",
	-- 				module = "blink.compat.source",
	-- 			},
	-- 		},
	-- 		-- completion = {
	-- 		-- 	enabled_providers = {
	-- 		-- 		"snippets",
	-- 		-- 		"luasnip",
	-- 		-- 		"lsp",
	-- 		-- 		"path",
	-- 		-- 		"buffer",
	-- 		-- 	},
	-- 		-- },
	-- 		-- optionally disable cmdline completions
	-- 		-- cmdline = {},
	-- 	},
	--
	-- 	-- snippets = {
	-- 	-- 	expand = function(snippet)
	-- 	-- 		require("luasnip").lsp_expand(snippet)
	-- 	-- 	end,
	-- 	-- 	active = function(filter)
	-- 	-- 		if filter and filter.direction then
	-- 	-- 			return require("luasnip").jumpable(filter.direction)
	-- 	-- 		end
	-- 	-- 		return require("luasnip").in_snippet()
	-- 	-- 	end,
	-- 	-- 	jump = function(direction)
	-- 	-- 		require("luasnip").jump(direction)
	-- 	-- 	end,
	-- 	-- },
	--
	-- 	completion = {
	-- 		accept = {
	-- 			-- experimental auto-brackets support
	-- 			auto_brackets = {
	-- 				enabled = false,
	-- 			},
	-- 		},
	-- 		menu = {
	-- 			draw = {
	-- 				treesitter = { "lsp" },
	-- 			},
	-- 		},
	-- 		documentation = {
	-- 			auto_show = true,
	-- 			auto_show_delay_ms = 200,
	-- 		},
	-- 		trigger = {
	-- 			show_on_insert_trigger_character = false,
	-- 		},
	-- 	},
	--
	-- 	appearance = {
	-- 		-- Sets the fallback highlight groups to nvim-cmp's highlight groups
	-- 		-- Useful for when your theme doesn't support blink.cmp
	-- 		-- will be removed in a future release
	-- 		use_nvim_cmp_as_default = true,
	-- 		-- Set to 'mono' for 'Nerd Font Mono' or 'normal' for 'Nerd Font'
	-- 		-- Adjusts spacing to ensure icons are aligned
	-- 		nerd_font_variant = "mono",
	-- 	},
	--
	-- 	-- experimental signature help support
	-- 	-- signature = { enabled = true },
	-- },
	-- config = function(_, opts)
	-- 	require("blink.cmp").setup(opts)
	-- end,
}
