return {
    -- "stevearc/oil.nvim",
    -- dependencies = {
    --     "nvim-tree/nvim-web-devicons"
    -- },
    -- config = function()
    --     require("oil").setup({
    --         default_file_explorer = true,
    --         delete_to_trash = true,
    --         skip_confirm_for_simple_edits = true,
    --         view_options = {
    --             show_hidden = true,
    --             natural_order = true,
    --             is_always_hidden = function(name, _)
    --                 return name == ".." or name == ".git" or name == ".DS_Store"
    --             end,
    --         },
    --         win_options = {
    --             wrap = true,
    --             winblend = 0,
    --         },
    --         keymaps = {
    --             ["<C-h>"] = false,
    --             ["<C-l>"] = false,
    --             ["<C-k>"] = false,
    --             ["<C-j>"] = false,
    --             ["<C-t>"] = false,
    --             ["<C-c>"] = false,
    --             ["q"] = "actions.close",
    --         },
    --     })
    --     this might work? idk havent tested just got it from claude, so far testing with mini files rn lets see how that goes
    --     vim.api.nvim_create_autocmd("User", {
    --         pattern = "OilRename",
    --         callback = function(event)
    --             -- Oil provides old_name and new_name in the data table
    --             Snacks.rename.on_rename_file(event.data.old_name, event.data.new_name)
    --         end,
    --     })
    --     vim.keymap.set("n", "-", "<CMD>Oil<CR>", { desc = "Open parent directory" })
    -- end,
}
